name: '이슈 생성'
description: 'Repo에 이슈를 생성하며, 생성된 이슈는 Jira와 연동됩니다.'
labels: [feat]
title: '이슈 이름을 작성해주세요'
body:
  - type: dropdown
    id: type
    attributes:
      label: '이슈 타입'
      description: '이슈의 타입을 설정'
      options:
        - epic
        - story
        - task
        - sub-task
    validations:
      required: true
      
  - type: input
    id: parentKey
    attributes:
      label: 'Ticket Number'
      description: '상위 작업의 Ticket Number'
      placeholder: 'FLINT-00'
    validations:
      required: true

  - type: input
    id: branch
    attributes:
      label: 'Branch'
      description: '작업할 브랜치 이름'
    validations:
      required: true
      
  - type: input
    id: description
    attributes:
      label: 'Description'
      description: '이슈에 대한 간략한 설명'
    validations:
      required: true

  - type: input
    id: period
    attributes:
      label: 'Period'
      description: '작업 기간'
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 'TODO'
      description: '작업목록 작성'
      value: |
        - [ ] Task1
        - [ ] Task2
    validations:
      required: true
